import canUseDOM from '../components/canUseDOM'
import { sampler } from '../components/rhythmical/instruments/sampler';

export const organ = {
  load: async () => {
    const samples = {
      C2: "../samples/organ/B4 Blues_02.mp3",
      Db2: "../samples/organ/B4 Blues_03.mp3",
      D2: "../samples/organ/B4 Blues_04.mp3",
      Eb2: "../samples/organ/B4 Blues_05.mp3",
      E2: "../samples/organ/B4 Blues_06.mp3",
      F2: "../samples/organ/B4 Blues_07.mp3",
      Gb2: "../samples/organ/B4 Blues_08.mp3",
      G2: "../samples/organ/B4 Blues_09.mp3",
      Ab2: "../samples/organ/B4 Blues_10.mp3",
      A2: "../samples/organ/B4 Blues_11.mp3",
      Bb2: "../samples/organ/B4 Blues_12.mp3",
      B2: "../samples/organ/B4 Blues_13.mp3",
      C3: "../samples/organ/B4 Blues_14.mp3",
      Db3: "../samples/organ/B4 Blues_15.mp3",
      D3: "../samples/organ/B4 Blues_16.mp3",
      Eb3: "../samples/organ/B4 Blues_17.mp3",
      E3: "../samples/organ/B4 Blues_18.mp3",
      F3: "../samples/organ/B4 Blues_19.mp3",
      Gb3: "../samples/organ/B4 Blues_20.mp3",
      G3: "../samples/organ/B4 Blues_21.mp3",
      Ab3: "../samples/organ/B4 Blues_22.mp3",
      A3: "../samples/organ/B4 Blues_23.mp3",
      Bb3: "../samples/organ/B4 Blues_24.mp3",
      B3: "../samples/organ/B4 Blues_25.mp3",
      C4: "../samples/organ/B4 Blues_26.mp3",
      Db4: "../samples/organ/B4 Blues_27.mp3",
      D4: "../samples/organ/B4 Blues_28.mp3",
      Eb4: "../samples/organ/B4 Blues_29.mp3",
      E4: "../samples/organ/B4 Blues_30.mp3",
      F4: "../samples/organ/B4 Blues_31.mp3",
      Gb4: "../samples/organ/B4 Blues_32.mp3",
      G4: "../samples/organ/B4 Blues_33.mp3",
      Ab4: "../samples/organ/B4 Blues_34.mp3",
      A4: "../samples/organ/B4 Blues_35.mp3",
      Bb4: "../samples/organ/B4 Blues_36.mp3",
      B4: "../samples/organ/B4 Blues_37.mp3",
      C5: "../samples/organ/B4 Blues_38.mp3",
      Db5: "../samples/organ/B4 Blues_39.mp3",
      D5: "../samples/organ/B4 Blues_40.mp3",
      Eb5: "../samples/organ/B4 Blues_41.mp3",
      E5: "../samples/organ/B4 Blues_42.mp3",
      F5: "../samples/organ/B4 Blues_43.mp3",
      Gb5: "../samples/organ/B4 Blues_44.mp3",
      G5: "../samples/organ/B4 Blues_45.mp3",
      Ab5: "../samples/organ/B4 Blues_46.mp3",
      A5: "../samples/organ/B4 Blues_47.mp3",
      Bb5: "../samples/organ/B4 Blues_48.mp3",
      B5: "../samples/organ/B4 Blues_49.mp3",
      C6: "../samples/organ/B4 Blues_50.mp3",
      Db6: "../samples/organ/B4 Blues_51.mp3",
      D6: "../samples/organ/B4 Blues_52.mp3",
      Eb6: "../samples/organ/B4 Blues_53.mp3",
      E6: "../samples/organ/B4 Blues_54.mp3",
      F6: "../samples/organ/B4 Blues_55.mp3",
      Gb6: "../samples/organ/B4 Blues_56.mp3",
      G6: "../samples/organ/B4 Blues_57.mp3",
      Ab6: "../samples/organ/B4 Blues_58.mp3",
      A6: "../samples/organ/B4 Blues_59.mp3",
      Bb6: "../samples/organ/B4 Blues_60.mp3",
      B6: "../samples/organ/B4 Blues_61.mp3",
      C7: "../samples/organ/B4 Blues_62.mp3",
    }
    return canUseDOM() && (await sampler(samples, { volume: -20 })()).toDestination();
  }
}