import canUseDOM from '../components/canUseDOM'
import { sampler } from '../components/rhythmical/instruments/sampler';

export const piano = {
  load: async () => {
    const samples = {
      C1: "../samples/piano/C1.mp3",
      Db1: "../samples/piano/Db1.mp3",
      D1: "../samples/piano/D1.mp3",
      Eb1: "../samples/piano/Eb1.mp3",
      E1: "../samples/piano/E1.mp3",
      F1: "../samples/piano/F1.mp3",
      Gb1: "../samples/piano/Gb1.mp3",
      G1: "../samples/piano/G1.mp3",
      Ab1: "../samples/piano/Ab1.mp3",
      A1: "../samples/piano/A1.mp3",
      Bb1: "../samples/piano/Bb1.mp3",
      B1: "../samples/piano/B1.mp3",
      C2: "../samples/piano/C2.mp3",
      Db2: "../samples/piano/Db2.mp3",
      D2: "../samples/piano/D2.mp3",
      Eb2: "../samples/piano/Eb2.mp3",
      E2: "../samples/piano/E2.mp3",
      F2: "../samples/piano/F2.mp3",
      Gb2: "../samples/piano/Gb2.mp3",
      G2: "../samples/piano/G2.mp3",
      Ab2: "../samples/piano/Ab2.mp3",
      A2: "../samples/piano/A2.mp3",
      Bb2: "../samples/piano/Bb2.mp3",
      B2: "../samples/piano/B2.mp3",
      C3: "../samples/piano/C3.mp3",
      Db3: "../samples/piano/Db3.mp3",
      D3: "../samples/piano/D3.mp3",
      Eb3: "../samples/piano/Eb3.mp3",
      E3: "../samples/piano/E3.mp3",
      F3: "../samples/piano/F3.mp3",
      Gb3: "../samples/piano/Gb3.mp3",
      G3: "../samples/piano/G3.mp3",
      Ab3: "../samples/piano/Ab3.mp3",
      A3: "../samples/piano/A3.mp3",
      Bb3: "../samples/piano/Bb3.mp3",
      B3: "../samples/piano/B3.mp3",
      C4: "../samples/piano/C4.mp3",
      Db4: "../samples/piano/Db4.mp3",
      D4: "../samples/piano/D4.mp3",
      Eb4: "../samples/piano/Eb4.mp3",
      E4: "../samples/piano/E4.mp3",
      F4: "../samples/piano/F4.mp3",
      Gb4: "../samples/piano/Gb4.mp3",
      G4: "../samples/piano/G4.mp3",
      Ab4: "../samples/piano/Ab4.mp3",
      A4: "../samples/piano/A4.mp3",
      Bb4: "../samples/piano/Bb4.mp3",
      B4: "../samples/piano/B4.mp3",
      C5: "../samples/piano/C5.mp3",
      Db5: "../samples/piano/Db5.mp3",
      D5: "../samples/piano/D5.mp3",
      Eb5: "../samples/piano/Eb5.mp3",
      E5: "../samples/piano/E5.mp3",
      F5: "../samples/piano/F5.mp3",
      Gb5: "../samples/piano/Gb5.mp3",
      G5: "../samples/piano/G5.mp3",
      Ab5: "../samples/piano/Ab5.mp3",
      A5: "../samples/piano/A5.mp3",
      Bb5: "../samples/piano/Bb5.mp3",
      B5: "../samples/piano/B5.mp3",
      C6: "../samples/piano/C6.mp3",
      Db6: "../samples/piano/Db6.mp3",
      D6: "../samples/piano/D6.mp3",
      Eb6: "../samples/piano/Eb6.mp3",
      E6: "../samples/piano/E6.mp3",
      F6: "../samples/piano/F6.mp3",
      Gb6: "../samples/piano/Gb6.mp3",
      G6: "../samples/piano/G6.mp3",
      Ab6: "../samples/piano/Ab6.mp3",
      A6: "../samples/piano/A6.mp3",
      Bb6: "../samples/piano/Bb6.mp3",
      B6: "../samples/piano/B6.mp3",
      C7: "../samples/piano/C7.mp3",
      Db7: "../samples/piano/Db7.mp3",
      D7: "../samples/piano/D7.mp3",
      Eb7: "../samples/piano/Eb7.mp3",
      E7: "../samples/piano/E7.mp3",
      F7: "../samples/piano/F7.mp3",
      Gb7: "../samples/piano/Gb7.mp3",
      G7: "../samples/piano/G7.mp3",
      Ab7: "../samples/piano/Ab7.mp3",
      A7: "../samples/piano/A7.mp3",
      Bb7: "../samples/piano/Bb7.mp3",
      B7: "../samples/piano/B7.mp3"
    }
    return canUseDOM() && (await sampler(samples, { volume: -20 })()).toDestination();
  }
}